### ISSUE TITLE
'Read'ing an azure.storage.Account crashes in terraform during migration.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi-terraform#226]
I have the following TS code in my app (inside @pulumi/cloud-azure to be specific):

```ts
            const result = await azure.storage.getAccount({
                name: storageAccountName,
                resourceGroupName: resourceGroupName,
            });

            console.log("getAccount result: " + JSON.stringify(result, null, 2));

            const account = azure.storage.Account.get(name, result.id);
```

The call to .getAccount succeeds and returns useful data.  However, the call to `Account.get` ends up crashing with the following stack:

<details>

```
info: panic: runtime error: index out of range
    goroutine 80 [running]:
    github.com/pulumi/pulumi-azure/vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm.migrateStorageAccountStateV0toV1(0xc4207aa3c0, 0x1, 0x1, 0x0)
    	/home/cyrusn/go/src/github.com/pulumi/pulumi-azure/vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_storage_account_migration.go:37 +0x338
    github.com/pulumi/pulumi-azure/vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm.resourceStorageAccountMigrateState(0x0, 0xc4207aa3c0, 0x1f9f940, 0xc420bac000, 0x300a7a0, 0x1ed1f00, 0x40d872)
    	/home/cyrusn/go/src/github.com/pulumi/pulumi-azure/vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_storage_account_migration.go:17 +0x1d1
    github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc4205f7f80, 0xc4207aa3c0, 0x1f9f940, 0xc420bac000, 0xc4203d2b30, 0x1, 0x1ed1fa0)
    	/home/cyrusn/go/src/github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:340 +0x293
    github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc4205ffb90, 0xc420633600, 0xc4207aa3c0, 0xc4203ee2a0, 0x0, 0xc4206e4360)
    	/home/cyrusn/go/src/github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:308 +0x9a
    github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.(*Provider).Read(0xc4203d02d0, 0x2f70080, 0xc420aff590, 0xc4207aa370, 0xc4203d02d0, 0x1, 0x1)
    	/home/cyrusn/go/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider.go:463 +0x63f
    github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Read_Handler.func1(0x2f70080, 0xc420aff590, 0x1f00040, 0xc4207aa370, 0x2f70080, 0xc420aff590, 0x2f75b60, 0x30090c8)
    	/home/cyrusn/go/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1239 +0x86
    github.com/pulumi/pulumi-azure/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x2f70080, 0xc420aff590, 0x1f00040, 0xc4207aa370, 0xc420beebc0, 0xc420beebe0, 0x0, 0x0, 0x2f5fc80, 0xc420217180)
    	/home/cyrusn/go/src/github.com/pulumi/pulumi-azure/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:61 +0x326
    github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Read_Handler(0x1f6f760, 0xc4203d02d0, 0x2f70080, 0xc420aff4d0, 0xc4207aa320, 0xc420289ec0, 0x0, 0x0, 0xc4203e6a90, 0x48efe4)
    	/home/cyrusn/go/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1241 +0x16d
    github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4200c0000, 0x2f74760, 0xc420080000, 0xc420bab700, 0xc420456db0, 0x2fdd418, 0x0, 0x0, 0x0)
    	/home/cyrusn/go/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:826 +0xab4
    github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4200c0000, 0x2f74760, 0xc420080000, 0xc420bab700, 0x0)
    	/home/cyrusn/go/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:1023 +0x1528
    github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc42040e120, 0xc4200c0000, 0x2f74760, 0xc420080000, 0xc420bab700)
    	/home/cyrusn/go/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:572 +0x9f
    created by github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/cyrusn/go/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:570 +0xa1
```
</details>

As we can see from the stack, we're doing:

`(*Provider).Read -> (*Provider).Refresh -> (*Resource).Refresh` which finally calls into Terraform with `resource_arm_storage_account_migration::migrateStorageAccountStateV0toV1`

The code for this is here: 

https://github.com/terraform-providers/terraform-provider-azurerm/blob/6def3d82391b2453e6bd9c27b98ef10774dd71ae/azurerm/resource_arm_storage_account_migration.go#L26-L42

And, effectively, is crashing because it expects to have an account_type field which it can split to learn the `account_tier` and `account_replication type`.  

--

Importantly, we're getting here because Terraform thinks we're on some v0 schema, and they're tring to migrate to the latest (v2) schema version:

https://github.com/terraform-providers/terraform-provider-azurerm/blob/6def3d82391b2453e6bd9c27b98ef10774dd71ae/azurerm/resource_arm_storage_account_migration.go#L12-L24

This is definitely busted as the instance value we have looks to already be at a later schema version since it already has `account_tier` and `account_replication_type` in it:

```json
{
      "accessTier": "Hot",
      "accountEncryptionSource": "Microsoft.Storage",
      "accountKind": "StorageV2",
      "accountReplicationType": "RAGRS"
```

--

I'm not sure if this is a bug in us, or in terraform itself.  Perhaps we're not passing in the right version info, and so it's defaulting back to `0`.  Or, maybe we're doing everything right, and terraform is just busted here.  I know too little about this part of the stack to know for certain.

**Comment by CyrusNajmabadi** [comment]
Tagging @lukehoban @pgavlin

**Comment by pgavlin** [comment]
I have confirmed that this is now fixed.
