### ISSUE TITLE
interface {} is schema.schemaMap, not *schema.schemaMap

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-terraform#229]
I hit the following error when updating a stack:

`info: panic: interface conversion: interface {} is schema.schemaMap, not *schema.schemaMap`

The full stack trace is below. I *believe* I passed bad properties to a resource, but haven't gotten far enough along to know for sure why this failed.

The program is:

**index.ts**

```typescript
// Copyright 2016-2017, Pulumi Corporation.  All rights reserved.

import * as azure from "@pulumi/azure";
import * as pulumi from "@pulumi/pulumi";
import * as config from "./config";

const kubernetesService = new azure.containerservice.KubernetesCluster("aksCluster", {
    resourceGroupName: config.resourceGroup.name,
    location: config.location,
    agentPoolProfile: {
        name: "aksagentpool",
        count: config.nodeCount,
        vmSize: config.nodeSize,
    },
    dnsPrefix: `${pulumi.getStack()}-kubernetes`,
    linuxProfile: {
        adminUsername: "aksUser",
        sshKeys: [{
            keyData: config.sshPublicKey,
        }],
    },
    servicePrincipal: {
        clientId: "", //config.clientId,
        clientSecret: "", //config.clientSecret,
    },
}); 

export const kubeConfigRaw = kubernetesService.kubeConfigRaw;
```

**config.ts**

```typescript
// Copyright 2016-2017, Pulumi Corporation.  All rights reserved.

import * as azure from "@pulumi/azure";
import * as pulumi from "@pulumi/pulumi";

// Parse and export configuration variables for this stack.
const config = new pulumi.Config();
export const clientId = config.require("clientId");
export const clientSecret = config.require("clientSecret");
export const location = config.get("location") || "East US";
export const nodeCount = config.getNumber("nodeCount") || 2;
export const nodeSize = config.get("nodeSize") || "Standard_D2_v2";
export const sshPublicKey = config.require("sshPublicKey");
export const resourceGroup = new azure.core.ResourceGroup("aks", { location });
```

I know that these properties are incorrect, so perhaps they are the culprit:

```
        clientId: "", //config.clientId,
        clientSecret: "", //config.clientSecret,
```

Here is the full stack trace:

```
info: panic: interface conversion: interface {} is schema.schemaMap, not *schema.schemaMap
    goroutine 83 [running]:
    github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform/helper/schema.(*schemaMap).DeepCopy(0xc4202a2608, 0xc420bc7ec0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:398 +0xa2
    github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.Diff(0xc42051f5f0, 0xc420955720, 0xc420bc7e90, 0x2dca0e0, 0x2cfc1a0, 0xc420906000, 0xc4208ef328, 0x19f0973, 0x2be3c80)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:440 +0xaea
    github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Diff(0xc42030be30, 0xc420955720, 0xc420bc7e90, 0x2cfc1a0, 0xc420906000, 0x1, 0x0, 0xc42084a370)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:250 +0x187
    github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Diff(0xc4202f9030, 0xc4208ef600, 0xc420955720, 0xc420bc7e90, 0x1, 0xc42084a370, 0xa2)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:296 +0xa4
    github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.(*Provider).Create(0xc42050a2d0, 0x3d938e0, 0xc420bc7b30, 0xc420bd8400, 0xc42050a2d0, 0x1, 0x1)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider.go:418 +0x55b
    github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Create_Handler.func1(0x3d938e0, 0xc420bc7b30, 0x2c27240, 0xc420bd8400, 0x3d938e0, 0xc420bc7b30, 0x3d99e60, 0x3e386f8)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1229 +0x86
    github.com/pulumi/pulumi-azure/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x3d938e0, 0xc420bc7b30, 0x2c27240, 0xc420bd8400, 0xc420861760, 0xc420861780, 0x0, 0x0, 0x3d80d20, 0xc42023bbd0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:61 +0x326
    github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Create_Handler(0x2cc94c0, 0xc42050a2d0, 0x3d938e0, 0xc4208e17a0, 0xc4209556d0, 0xc420320000, 0x0, 0x0, 0x19d9dfabc4321a6d, 0x6c8be9e4c8b38052)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1231 +0x16d
    github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4200deb40, 0x3d98600, 0xc42009e000, 0xc420969400, 0xc4205e37d0, 0x3e0c520, 0x0, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:826 +0xab4
    github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4200deb40, 0x3d98600, 0xc42009e000, 0xc420969400, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:1023 +0x1528
    github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc42008d520, 0xc4200deb40, 0x3d98600, 0xc42009e000, 0xc420969400)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:572 +0x9f
    created by github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:570 +0xa1

  azure:containerservice:KubernetesCluster: aksCluster
    error: Plan apply failed: transport is closing
```

**Comment by joeduffy** [comment]
I believe this only triggers for diffs on resources with custom diff logic, due to this line:

/Users/joeduffy/dev/code/src/github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:440

```
if !result.DestroyTainted && customizeDiff != nil {
```

This calls `DeepCopy` which copies the structure with `*copy.(*schemaMap)`.

**Comment by joeduffy** [comment]
I've manually repaired the lockfile to fix this in the Azure repo https://github.com/pulumi/pulumi-azure/pull/89, but will leave this bug open to track fixing this in a more robust way. For instance, would constraining dependencies for `copystructure` (and `reflectwalk`) in this repo solve the issue?

**Comment by CyrusNajmabadi** [comment]
I'm now hitting this over in azure with: https://travis-ci.com/pulumi/pulumi-cloud/builds/88927816

> [ umi-cloud/azure/examples/topic ]  +  pulumi:pulumi:Stack topic-p-it-travis-job-topic-c90eebdc creating 1 info message. info: panic: interface conversion: interface {} is schema.schemaMap, not *schema.schemaMap

Did we somehow break this?
