### ISSUE TITLE
Improve user experience in the face of TF provider bugs

### ISSUE THREAD

**Issue by jen20** [pulumi/pulumi-terraform#332]
We liberally assert throughout `tfbridge` - which is good - except that the user experience of a panic with a backtrace is not particularly friendly when Pulumi users encounter such a bug.

For example, the following program:

```typescript
import * as azure from "@pulumi/azure";

const badVaultId = `/subscriptions/${azure.config.subscriptionId}/resourceGroups/myrg/providers/Microsoft.KeyVault/vaults/idontexist`;

new azure.keyvault.AccessPolicy("policy", {
    keyVaultId: badVaultId,
    tenantId: <string>azure.config.tenantId,
    objectId: "11111111-1111-1111-1111-111111111111", // Wouldn't work anyway, probably, but not the issue here
    keyPermissions: ['get', 'list'],
    certificatePermissions: ['get', 'list'],
    secretPermissions: ['get', 'list']
});
```

Run with `pulumi up`, gives:

``` shell
$ pulumi up                                                                                                                                                   ⇡ 
Previewing update (dev):

     Type                            Name           Plan
 +   pulumi:pulumi:Stack             azure-183-dev  create
 +   └─ azure:keyvault:AccessPolicy  policy         create

Resources:
    + 2 to create

Do you want to perform this update? yes
Updating (dev):

     Type                            Name           Status                  Info
 +   pulumi:pulumi:Stack             azure-183-dev  created                 22 messages
 +   └─ azure:keyvault:AccessPolicy  policy         **creating failed**     1 error

Diagnostics:
  pulumi:pulumi:Stack (azure-183-dev):
    panic: fatal: An assertion has failed: expected non-nil error with nil state during Create
    goroutine 30 [running]:
    github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/pkg/util/contract.failfast(0xc000c58870, 0x4c)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23 +0xe9
    github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/pkg/util/contract.Assertf(0xc00068b300, 0x33b8791, 0x33, 0x0, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/pkg/util/contract/assert.go:33 +0x126
    github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.(*Provider).Create(0xc00069ce10, 0x3713fc0, 0xc000ac4570, 0xc0011fd580, 0xc00069ce10, 0x1, 0x1)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider.go:566 +0xbda
    github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Create_Handler.func1(0x3713fc0, 0xc000ac4570, 0x3225660, 0xc0011fd580, 0x3713fc0, 0xc000ac4570, 0x372d220, 0x50acde0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1229 +0x86
    github.com/pulumi/pulumi-azure/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x3713fc0, 0xc000ac4570, 0x3225660, 0xc0011fd580, 0xc0011ffde0, 0xc0011ffe00, 0x0, 0x0, 0x36feea0, 0xc0002c2c10)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:57 +0x2b0
    github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Create_Handler(0x32bc200, 0xc00069ce10, 0x3713fc0, 0xc000ac4270, 0xc000b9c460, 0xc00000a6a0, 0x0, 0x0, 0xc00091e380, 0x1bb)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1231 +0x158
    github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002ab980, 0x372aa00, 0xc00050a480, 0xc000925900, 0xc0006af5f0, 0x5080ae0, 0x0, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:966 +0x4a2
    github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0002ab980, 0x372aa00, 0xc00050a480, 0xc000925900, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:1245 +0xd58
    github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0002984f0, 0xc0002ab980, 0x372aa00, 0xc00050a480, 0xc000925900)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:685 +0x9f
    created by github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:683 +0xa1

  azure:keyvault:AccessPolicy (policy):
    error: Plan apply failed: transport is closing

Resources:
    + 1 created

Duration: 5s

Permalink: https://app.pulumi.com/jen20/azure-183/dev/updates/20
error: update failed
```

The panic comes from the assertion here:

https://github.com/pulumi/pulumi-terraform/blob/master/pkg/tfbridge/provider.go#L564-L568

We should likely handle this with an error rather than a panic in order to present a better UX. @pgavlin, any additional thoughts around this?

**Comment by stack72** [comment]
I am going to close this out - it's actually related to #2628 and we can see that we now return a nicer message to the user

If this surfaces again, then we can reinvestigate and look further
