### ISSUE TITLE
`panic: runtime error: index out of range` in `makePropertyDiff`

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-terraform#402]
The AWS provider is now hitting this in master:

```
[ /pulumi-aws/examples/webserver ]     panic: runtime error: index out of range
[ /pulumi-aws/examples/webserver ]     goroutine 63 [running]:
[ /pulumi-aws/examples/webserver ]     github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.makePropertyDiff(0xc0008a9480, 0xf, 0xc0008d8ca0, 0xe, 0x3ed9ee0, 0xc000887ae0, 0xc000887ba0, 0xc000dd0f60, 0xc0005ce600, 0x0, ...)
[ /pulumi-aws/examples/webserver ]     	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/diff.go:129 +0x11ec
[ /pulumi-aws/examples/webserver ]     github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.makeDetailedDiff(0xc0005c0270, 0xc000717980, 0xc0009ed2c0, 0xc0009ede00, 0xc000887ba0, 0xc0008bfd80)
[ /pulumi-aws/examples/webserver ]     	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/diff.go:216 +0x268
[ /pulumi-aws/examples/webserver ]     github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.(*Provider).Diff(0xc0005ea480, 0x56bdf40, 0xc0009ed230, 0xc000819220, 0xc0005ea480, 0x44c0b01, 0xc000094b80)
[ /pulumi-aws/examples/webserver ]     	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider.go:577 +0xa9a
[ /pulumi-aws/examples/webserver ]     github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Diff_Handler.func1(0x56bdf40, 0xc0009ed230, 0x4bf3340, 0xc000819220, 0x4c36380, 0x934ade8, 0x56bdf40, 0xc0009ed230)
[ /pulumi-aws/examples/webserver ]     	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1498 +0x86
[ /pulumi-aws/examples/webserver ]     github.com/pulumi/pulumi-aws/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x56bdf40, 0xc0009ec5d0, 0x4bf3340, 0xc000819220, 0xc000886820, 0xc000886840, 0x0, 0x0, 0x562ada0, 0xc0004318f0)
[ /pulumi-aws/examples/webserver ]     	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:61 +0x360
[ /pulumi-aws/examples/webserver ]     github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Diff_Handler(0x4c9f360, 0xc0005ea480, 0x56bdf40, 0xc0009ec5d0, 0xc0008191d0, 0xc0007692c0, 0x56bdf40, 0xc0009ec5d0, 0xc00069a300, 0x6d8)
[ /pulumi-aws/examples/webserver ]     	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1500 +0x158
[ /pulumi-aws/examples/webserver ]     github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004e2780, 0x56e0ca0, 0xc0004e3080, 0xc0005bd800, 0xc000772f60, 0x931cf18, 0x0, 0x0, 0x0)
[ /pulumi-aws/examples/webserver ]     	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:972 +0x470
[ /pulumi-aws/examples/webserver ]     github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0004e2780, 0x56e0ca0, 0xc0004e3080, 0xc0005bd800, 0x0)
[ /pulumi-aws/examples/webserver ]     	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:1252 +0xda6
[ /pulumi-aws/examples/webserver ]     github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0006c1010, 0xc0004e2780, 0x56e0ca0, 0xc0004e3080, 0xc0005bd800)
[ /pulumi-aws/examples/webserver ]     	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:691 +0x9f
[ /pulumi-aws/examples/webserver ]     created by github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
[ /pulumi-aws/examples/webserver ]     	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:689 +0xa1
[ /pulumi-aws/examples/webserver ]  
```

**Comment by stack72** [comment]
FYI, this is the only one of the providers hitting this issue! I released 15 providers earlier... and none of them seem to hit this

**Comment by pgavlin** [comment]
Looking into it now.
