### ISSUE TITLE
Panic in Create

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-terraform#405]
A user hit this panic in `Create`:

```
panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1aec85c]
    goroutine 122 [running]:
    github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc000689700, 0xc0008f1770, 0x0, 0x4a7a000, 0xc00034bb00, 0x1, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:235 +0x9c
    github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc00073f300, 0xc000ad7840, 0xc0008f1770, 0x0, 0x0, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:285 +0x18f
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.(*Provider).Create(0xc0000e9c20, 0x62b45a0, 0xc000b96de0, 0xc0007d0800, 0xc0000e9c20, 0x50b8301, 0xc0007d0c40)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider.go:611 +0x550
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Create_Handler.func1(0x62b45a0, 0xc000b96de0, 0x5756de0, 0xc0007d0800, 0x582d200, 0x9f3f7e0, 0x62b45a0, 0xc000b96de0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1516 +0x86
    github.com/pulumi/pulumi-aws/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x62b45a0, 0xc000b96c90, 0x5756de0, 0xc0007d0800, 0xc0008e7c80, 0xc0008e7ca0, 0x0, 0x0, 0x62217a0, 0xc000078740)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:61 +0x360
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Create_Handler(0x58965c0, 0xc0000e9c20, 0x62b45a0, 0xc000b96c90, 0xc0008f15e0, 0xc0002bc020, 0x62b45a0, 0xc000b96c90, 0xc000bcca00, 0x78)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1518 +0x158
    github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003a3380, 0x62d7580, 0xc0005a1680, 0xc0006f6100, 0xc0005ec8d0, 0x9f11d90, 0x0, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:972 +0x470
    github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0003a3380, 0x62d7580, 0xc0005a1680, 0xc0006f6100, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:1252 +0xda6
    github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000e2090, 0xc0003a3380, 0x62d7580, 0xc0005a1680, 0xc0006f6100)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:691 +0x9f
    created by github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:689 +0xa1
```

From code like this:

```
import pulumi
from pulumi_aws import guardduty
from pulumi_aws import securityhub

config = pulumi.Config("security")
env = config.require("env")
prefix = f"security-{env}"

guardduty.Detector(
    resource_name=f"{prefix}-guardduty",
    enable=True,
)

securityhub.Account(
    resource_name=f"{prefix}-securityhub",
)
```

```

**Comment by joeduffy** [comment]
This doesn't appear to be a new bug, as it repros with some older versions:

```
pulumi==0.16.14
pulumi_aws==0.17.0
```

**Comment by joeduffy** [comment]
It appears we don't initialize the `Meta` dictionary here:

https://github.com/pulumi/pulumi-terraform/blob/629f7c54269d6be5b5cb26d1f68678b990326e35/pkg/tfbridge/provider.go#L599

This should be as simple as changing `terraform.InstanceState{}` to `terraform.InstanceState{Meta: make(map[string]interface{})}`, I believe.
